export enum CategoryActionTypes{
    FET_CATEGORIES_START = "category/FET_CATEGORIES_START",
    FET_CATEGORIES_SUCCESS = "category/FET_CATEGORIES_SUCCESS",
    FET_CATEGORIES_ERROR = "category/FET_CATEGORIES_ERROR"
 }
      